; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:esp32-s3-devkitc-1]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino

; --- Configuración de Memoria N16R8 (16MB Flash / 8MB PSRAM) ---
board_build.arduino.memory_type = qio_opi ; Crucial para activar la PSRAM Octal
board_build.f_flash = 80000000L
board_build.flash_mode = qio
board_upload.flash_size = 16MB

; --- Librerías ---
lib_deps = 
    https://github.com/eclipse-zenoh/zenoh-pico
    https://github.com/eProsima/Micro-CDR
    tzapu/WiFiManager @ ^2.0.17
    https://github.com/adafruit/Adafruit-PWM-Servo-Driver-Library

; --- Flags de Compilación ---
build_flags = 
    -I include
    -D ARDUINO_USB_MODE=1
    -D ARDUINO_USB_CDC_ON_BOOT=1
    -D BOARD_HAS_PSRAM            ; Indica al código que use los 8MB de RAM extra
    -mfix-esp32-psram-cache-issue ; Parche de seguridad para acceso a PSRAM
    -D CORE_DEBUG_LEVEL=3

; --- Monitor y Carga ---
monitor_speed = 115200
monitor_filters = esp32_exception_decoder
upload_speed = 921600